name: nextcloud

services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:${NEXTCLOUD_AIO_TAG}
    container_name: nextcloud-aio-mastercontainer
    restart: unless-stopped
    init: true
    environment:
      APACHE_PORT: ${NEXTCLOUD_APACHE_PORT}
      APACHE_IP_BINDING: 0.0.0.0
      NEXTCLOUD_DATADIR: ${NEXTCLOUD_DATADIR}
    ports:
      - "${NEXTCLOUD_AIO_PORT}:8080"
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  nextcloud_aio_mastercontainer:
