name: nextcloud

services:
  nextcloud-aio-mastercontainer:
    image: ${NEXTCLOUD_AIO_IMAGE}
    container_name: nextcloud-aio-mastercontainer
    restart: unless-stopped
    init: true
    environment:
      APACHE_PORT: ${NEXTCLOUD_APACHE_PORT}
      APACHE_IP_BINDING: 0.0.0.0
      NEXTCLOUD_DATADIR: ${NEXTCLOUD_DATADIR}
      SKIP_DOMAIN_VALIDATION: ${NEXTCLOUD_SKIP_DOMAIN_VALIDATION}
    ports:
    - "${NEXTCLOUD_AIO_PORT}:8080"
    volumes:
    - nextcloud_aio_mastercontainer:/mnt/docker-aio-config
    - /var/run/docker.sock:/var/run/docker.sock:ro

    healthcheck:
      test:
      - CMD
      - curl
      - -k
      - -f
      - https://localhost:8080/
      interval: 60s
      timeout: 10s
      retries: 3
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
