name: jellyfin

services:
  jellyfin:
    image: jellyfin/jellyfin:${JELLYFIN_TAG}
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "${JELLYFIN_PORT}:8096"
    volumes:
      - ${JELLYFIN_CONFIG_PATH}:/config
      - ${JELLYFIN_CACHE_PATH}:/cache
      - ${JELLYFIN_MEDIA_PATH}:/media:ro
