name: rustdesk

services:
  hbbs:
    container_name: rustdesk-hbbs
    image: rustdesk/rustdesk-server:${RUSTDESK_VERSION}
    command: hbbs -r ${RUSTDESK_RELAY_HOST}:21117
    environment:
      - ALWAYS_USE_RELAY=${ALWAYS_USE_RELAY}
    volumes:
      - ${RUSTDESK_DATA_DIR}:/root
    network_mode: "host"
    depends_on:
      - hbbr
    restart: unless-stopped

  hbbr:
    container_name: rustdesk-hbbr
    image: rustdesk/rustdesk-server:${RUSTDESK_VERSION}
    command: hbbr
    volumes:
      - ${RUSTDESK_DATA_DIR}:/root
    network_mode: "host"
    restart: unless-stopped
